### PR TITLE
Add 'custom' video type to publishers and subscribers state objects

### PR DESCRIPTION
**Pull request by ytzvan**
## What's in this pull request?

> add  'custom' type to publishers and subscribers

### CODE REVIEW

**Review by ggoldens — APPROVED** [review]
LGTM

**Review by MichaelJolley — CHANGES_REQUESTED** [review]
Nice addition @ytzvan!

@ggoldens I'd love your input on this, but this seems like a change we should add to the sdk-wrapper state object as well.

Also, we need to update the README with the updated property. Specifically, https://github.com/opentok/accelerator-core-js#events

**Comment by ytzvan** [comment]
@MichaelJolley thanks for your feedback. I updated the PR.

**Review by MichaelJolley — APPROVED** [review]
Great work @ytzvan!  Thanks for contributing.

bitmoji

**Pull request merged**
